Allow to append to CFLAGS, LDFLAGS and NVCCFLAGS
Currently, `make CFLAGS=<new-flags>` overrides any values of CFLAGS set in the
Makefile and will result in an error referring to missing headers:

```
$ make CFLAGS=-std=c++11
g++ -std=c++11 -c gpu_burn-drv.cpp
gpu_burn-drv.cpp:61:23: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
                       ^
compilation terminated.
make: *** [gpu_burn-drv.o] Error 1
```
This change adds the "override" directive
(https://www.gnu.org/software/make/manual/make.html#Override-Directive) to all
Makefile variables specified as appendable in the README.